import { literal } from '../spec/schema-to-zod.js';

function toolRegistration(tool) {
  return `
server.tool(
  {
    name: ${literal(tool.name)},
    title: ${literal(tool.title)},
    description: ${literal(tool.description)},
    inputSchema: ${tool.zodSchema},
    annotations: ${JSON.stringify(tool.annotations)},
  },
  (params) => runTool(${literal(tool.name)}, params),
);`;
}

/** `src/index.js` of the generated server, written against the mcp-use 2.x API. */
export function generateServerIndex(serverName, tools, baseUrl, port) {
  return `#!/usr/bin/env node

/**
 * ${serverName.replace(/\*\//g, '* /')} — MCP server (${tools.length} tools), generated by api2ai.
 *
 *   npm start      serve on http://localhost:${port}/mcp
 *   npm run dev    hot reload + Inspector at /mcp/inspector (mcp-use dev)
 */

import { realpathSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { MCPServer } from 'mcp-use';
import { z } from 'zod';
import { executeRequest } from './http-client.js';
import { toolConfigMap } from './tools-config.js';
import { assertAllowedBaseUrl, checkToolPolicy } from './policy.js';

// ============================================================================
// Configuration
// ============================================================================

const PORT = Number.parseInt(process.env.PORT || '${port}', 10);

const apiConfig = {
  baseUrl: process.env.API_BASE_URL || ${baseUrl ? literal(baseUrl) : 'null'},
  headers: {},
};

if (process.env.API_KEY) {
  apiConfig.headers['Authorization'] = \`Bearer \${process.env.API_KEY}\`;
}

if (process.env.API_AUTH_HEADER) {
  const [key, ...valueParts] = process.env.API_AUTH_HEADER.split(':');
  const value = valueParts.join(':'); // values may contain colons
  if (key && value) apiConfig.headers[key.trim()] = value.trim();
}

if (apiConfig.baseUrl) assertAllowedBaseUrl(apiConfig.baseUrl);

// mcp-use matches allowedOrigins/allowedHosts by hostname; accept full URLs too.
const hostnames = (list) => (list || '')
  .split(',')
  .map(s => s.trim())
  .filter(Boolean)
  .map(s => { try { return new URL(s).hostname; } catch { return s; } });

const allowedOrigins = hostnames(process.env.ALLOWED_ORIGINS);
const allowedHosts = hostnames(process.env.MCP_URL);

// ============================================================================
// Server
// ============================================================================

const server = new MCPServer({
  name: ${literal(serverName)},
  version: '1.0.0',
  description: 'MCP server generated from an OpenAPI specification',
  port: PORT,
  ...(allowedOrigins.length > 0 && { allowedOrigins }),
  ...(allowedHosts.length > 0 && { allowedHosts }),
});

const errorResult = (message) => ({ isError: true, content: [{ type: 'text', text: message }] });

/** Policy check → upstream call → MCP tool result. Shared by every tool. */
async function runTool(name, params) {
  const toolConfig = toolConfigMap.get(name);
  try {
    checkToolPolicy(toolConfig);
    const result = await executeRequest(toolConfig, params, apiConfig);
    const body = typeof result.data === 'string' ? result.data : JSON.stringify(result.data, null, 2);

    if (!result.ok) {
      return errorResult(\`Error: \${result.status} \${result.statusText}\\n\${body}\`);
    }
    // Objects and arrays also go out as structuredContent for clients that use it.
    return typeof result.data === 'object' && result.data !== null
      ? { content: [{ type: 'text', text: body }], structuredContent: result.data }
      : { content: [{ type: 'text', text: body || \`\${result.status} \${result.statusText}\` }] };
  } catch (err) {
    return errorResult(err?.message || String(err));
  }
}

// ============================================================================
// Tools
// ============================================================================
${tools.map(toolRegistration).join('\n')}

export default server;

// ============================================================================
// Start — only when run directly; \`mcp-use dev\` imports the default export.
// ============================================================================

const isMain = Boolean(process.argv[1]) && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
  const { url } = await server.listen(PORT);
  console.log(\`
🚀 ${serverName.replace(/[`$\\]/g, '\\$&')} MCP server
   MCP endpoint: \${url}
   Tools:        ${tools.length}
   API base:     \${apiConfig.baseUrl || 'not configured (set API_BASE_URL)'}
   Policy:       ALLOW_RESTRICTED_TOOLS=\${process.env.ALLOW_RESTRICTED_TOOLS || 'false'}, REQUIRE_APPROVALS=\${process.env.REQUIRE_APPROVALS || 'true'}
\`);
}
`;
}
