// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from 'api2client';
import type { ListUsersError, ListUsersResponse, GetUserData, GetUserError, GetUserResponse, ListPostsData, ListPostsError, ListPostsResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * List every user
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListUsersResponse, ListUsersError, ThrowOnError>({
        ...options,
        url: '/users'
    });
};

/**
 * Fetch one user by id
 */
export const getUser = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserResponse, GetUserError, ThrowOnError>({
        ...options,
        url: '/users/{id}'
    });
};

/**
 * List posts, optionally filtered by author
 */
export const listPosts = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<ListPostsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListPostsResponse, ListPostsError, ThrowOnError>({
        ...options,
        url: '/posts'
    });
};