// This file is auto-generated by @hey-api/openapi-ts

export type Error = {
    /**
     * What went wrong
     */
    message?: string;
};

/**
 * Something a user wrote
 */
export type Post = {
    /**
     * Unique id
     */
    id: number;
    /**
     * Who wrote it
     */
    userId: number;
    /**
     * Headline
     */
    title: string;
    /**
     * Full text
     */
    body?: string;
};

/**
 * One person in the directory
 */
export type User = {
    /**
     * Unique id
     */
    id: number;
    /**
     * Full name
     */
    name: string;
    /**
     * Login handle
     */
    username?: string;
    /**
     * Contact address
     */
    email: string;
    /**
     * Personal site
     */
    website?: string;
};

export type ListUsersResponse = (Array<User>);

export type ListUsersError = unknown;

export type GetUserData = {
    path: {
        /**
         * The user's id
         */
        id: number;
    };
};

export type GetUserResponse = (User);

export type GetUserError = (Error);

export type ListPostsData = {
    query?: {
        /**
         * Only posts written by this user
         */
        userId?: number;
    };
};

export type ListPostsResponse = (Array<Post>);

export type ListPostsError = unknown;